/**
 * Created by DCLab on 12/6/2015.
 */
var provinces = [
    {"province_code":"11","province":"北京市"},
    {"province_code":"12","province":"天津市"},
    {"province_code":"13","province":"河北省"},
    {"province_code":"14","province":"山西省"},
    {"province_code":"15","province":"内蒙古自治区"},
    {"province_code":"21","province":"辽宁省"},
    {"province_code":"22","province":"吉林省"},
    {"province_code":"23","province":"黑龙江省"},
    {"province_code":"31","province":"上海市"},
    {"province_code":"32","province":"江苏省"},
    {"province_code":"33","province":"浙江省"},
    {"province_code":"34","province":"安徽省"},
    {"province_code":"35","province":"福建省"},
    {"province_code":"36","province":"江西省"},
    {"province_code":"37","province":"山东省"},
    {"province_code":"41","province":"河南省"},
    {"province_code":"42","province":"湖北省"},
    {"province_code":"43","province":"湖南省"},
    {"province_code":"44","province":"广东省"},
    {"province_code":"45","province":"广西壮族自治区"},
    {"province_code":"46","province":"海南省"},
    {"province_code":"50","province":"重庆市"},
    {"province_code":"51","province":"四川省"},
    {"province_code":"52","province":"贵州省"},
    {"province_code":"53","province":"云南省"},
    {"province_code":"54","province":"西藏自治区"},
    {"province_code":"61","province":"陕西省"},
    {"province_code":"62","province":"甘肃省"},
    {"province_code":"63","province":"青海省"},
    {"province_code":"64","province":"宁夏回族自治区"},
    {"province_code":"65","province":"新疆维吾尔自治区"},
    {"province_code":"66","province":"新疆生产建设兵团"},
    {"province_code":"71","province":"台湾省"},
    {"province_code":"81","province":"香港特别行政区"},
    {"province_code":"82","province":"澳门特别行政区"},
]
var towns = [
    {"town_code":"001","town":"定海路街道"},
    {"town_code":"006","town":"平凉路街道"},
    {"town_code":"008","town":"江浦路街道"},
    {"town_code":"009","town":"四平路街道 "},
    {"town_code":"012","town":" 控江路街道"},
    {"town_code":"013","town":"长白新村街道"},
    {"town_code":"015","town":"延吉新村街道"},
    {"town_code":"016","town":"殷行街道"},
    {"town_code":"018","town":"大桥街道"},
    {"town_code":"019","town":"五角场街道"},
    {"town_code":"020","town":"新江湾城街道"},
    {"town_code":"101","town":"五角场镇"},
]

